## Docker Compose for development
version: "3"
services:
  db:
    image: obserfy/postgres-dev:latest
    container_name: grayson-postgres
    environment:
      POSTGRES_MULTIPLE_DATABASES: main
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - grayson-db:/var/lib/postgresql/data

volumes:
  grayson-db:
