## Docker Compose for development
version: "3"
services:
  db:
    image: obserfy/postgres-dev:latest
    environment:
      POSTGRES_MULTIPLE_DATABASES: main
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - grayson-db:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    entrypoint: sh
    command: -c 'mkdir -p /data/grayson && /usr/bin/minio server /data'
    environment:
      MINIO_HTTP_TRACE: "/dev/stdout"
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
      MINIO_BUCKET_LOCATION: us-east-1
    ports:
      - 9000:9000
    volumes:
      - grayson-minio:/data

volumes:
  grayson-db:
  grayson-minio:
