# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  deploy:
    name: Deploy grayson
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Create sentry.properties
        run: |
          echo defaults.url=$SENTRY_URL >> sentry.properties
          echo defaults.org=$SENTRY_ORG >> sentry.properties
          echo defaults.project=$SENTRY_PROJECT >> sentry.properties
          echo auth.token=$SENTRY_AUTH_TOKEN >> sentry.properties
          echo NEXT_PUBLIC_S3_PREFIX=$NEXT_PUBLIC_S3_PREFIX >> .env.local
        env:
          NEXT_PUBLIC_S3_PREFIX: "https://grayson-media.sgp1.cdn.digitaloceanspaces.com"
          SENTRY_URL: https://sentry.io/
          SENTRY_ORG: grayson-ga
          SENTRY_PROJECT: grayson
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DOCKER_BUILDKIT: 1
        with:
          args: "deploy"
